driver:
  aws_ssh_key_id: Ram_Keys
  region: us-east-1
  availability_zone: c
  subnet_id: subnet-5bd95010
  image_id: ami-66ca1419
  security_group_ids: ["sg-0101ac78791a371f7"]

transport:
  ssh_key: /Users/ramachandra/.ssh/RamKeyPair.pem

